In [3]:
import pandas as pd
import os

## Container * (Area / Image Area)

### Subdistrict

In [ ]:
df_container = pd.read_csv(os.path.join('Data','Container Density','Subdistrict level','container_Krabi_subdist.csv'))
df_container = df_container.drop('Unnamed: 0', axis = 1)
df_container['addrcode'] = df_container['addrcode'].astype(str)
df_container.head()

In [ ]:
df_area = pd.read_csv(os.path.join('Data','Area and GSV','image_coverage','image_coverage_krabi.csv'))
df_area = df_area.drop(['Unnamed: 0', 'image_coverage'], axis = 1)
df_area['addrcode'] = df_area['addrcode'].astype(str)
df_area['area/image'] = df_area['land_area'] / df_area['image_area']
df_area['area/image'] = df_area['area/image'].round(2)
df_area.head()

In [ ]:
df_container_area = pd.merge(df_area,df_container, how = 'inner')
df_container_area.head()

In [ ]:
df_container_area['bin_ai'] = df_container_area['bin']* df_container_area['area/image']
df_container_area['bin_ai'] = df_container_area['bin_ai'].round(3)
df_container_area['bowl_ai'] = df_container_area['bowl']* df_container_area['area/image']
df_container_area['bowl_ai'] = df_container_area['bowl_ai'].round(3)
df_container_area['bucket_ai'] = df_container_area['bucket']* df_container_area['area/image']
df_container_area['bucket_ai'] = df_container_area['bucket_ai'].round(3)
df_container_area['misc_short_ai'] = df_container_area['misc_short']* df_container_area['area/image']
df_container_area['misc_short_ai'] = df_container_area['misc_short_ai'].round(3)
df_container_area['jar_ai'] = df_container_area['jar']* df_container_area['area/image']
df_container_area['jar_ai'] = df_container_area['jar_ai'].round(3)
df_container_area['pottedplant_ai'] = df_container_area['pottedplant']* df_container_area['area/image']
df_container_area['pottedplant_ai'] = df_container_area['pottedplant_ai'].round(3)
df_container_area['tire_ai'] = df_container_area['tire']* df_container_area['area/image']
df_container_area['tire_ai'] = df_container_area['tire_ai'].round(3)
df_container_area['misc_tall_ai'] = df_container_area['misc_tall']* df_container_area['area/image']
df_container_area['misc_tall_ai'] = df_container_area['misc_tall_ai'].round(3)
df_container_area['total_ai'] = df_container_area['total']* df_container_area['area/image']
df_container_area['total_ai'] = df_container_area['total_ai'].round(3)

In [ ]:
df_container_area.head()
df_container_area.to_csv('container_area_krabi_subdist.csv', encoding = 'utf-8')

### District

In [ ]:
aggregation_function = {'land_area': 'sum', 'image_area' : 'sum', 'bin' : 'sum', 'bowl' : 'sum', 'bucket' : 'sum', 'misc_short' : 'sum', 'jar' : 'sum', 'pottedplant' : 'sum', 'tire' : 'sum', 'misc_tall' : 'sum', 'total' : 'sum'}
df_container_area_dist = df_container_area.groupby([df_container_area['addrcode'].str[:4]]).aggregate(aggregation_function).reset_index()
df_container_area_dist['area/image'] = df_container_area_dist['land_area']/df_container_area_dist['image_area']
df_container_area_dist['area/image'] = df_container_area_dist['area/image'].round(2)
df_container_area_dist = df_container_area_dist[['addrcode','land_area','image_area','area/image','bin','bowl','bucket','misc_short','jar','pottedplant','tire','misc_tall','total']]
df_container_area_dist

In [ ]:
df_container_area_dist['bin_ai'] = df_container_area_dist['bin']* df_container_area_dist['area/image']
df_container_area_dist['bin_ai'] = df_container_area_dist['bin_ai'].round(3)
df_container_area_dist['bowl_ai'] = df_container_area_dist['bowl']* df_container_area_dist['area/image']
df_container_area_dist['bowl_ai'] = df_container_area_dist['bowl_ai'].round(3)
df_container_area_dist['bucket_ai'] = df_container_area_dist['bucket']* df_container_area_dist['area/image']
df_container_area_dist['bucket_ai'] = df_container_area_dist['bucket_ai'].round(3)
df_container_area_dist['misc_short_ai'] = df_container_area_dist['misc_short']* df_container_area_dist['area/image']
df_container_area_dist['misc_short_ai'] = df_container_area_dist['misc_short_ai'].round(3)
df_container_area_dist['jar_ai'] = df_container_area_dist['jar']* df_container_area_dist['area/image']
df_container_area_dist['jar_ai'] = df_container_area_dist['jar_ai'].round(3)
df_container_area_dist['pottedplant_ai'] = df_container_area_dist['pottedplant']* df_container_area_dist['area/image']
df_container_area_dist['pottedplant_ai'] = df_container_area_dist['pottedplant_ai'].round(3)
df_container_area_dist['tire_ai'] = df_container_area_dist['tire']* df_container_area_dist['area/image']
df_container_area_dist['tire_ai'] = df_container_area_dist['tire_ai'].round(3)
df_container_area_dist['misc_tall_ai'] = df_container_area_dist['misc_tall']*df_container_area_dist['area/image']
df_container_area_dist['misc_tall_ai'] = df_container_area_dist['misc_tall_ai'].round(3)
df_container_area_dist['total_ai'] = df_container_area_dist['total']* df_container_area_dist['area/image']
df_container_area_dist['total_ai'] = df_container_area_dist['total_ai'].round(3)

In [ ]:
df_container_area_dist.head()
df_container_area_dist.to_csv('container_area_krabi_dist.csv', encoding = 'utf-8')

## Image Area / Area * Population

### Subdistrict

In [ ]:
df_area = pd.read_csv(os.path.join('Data','Area and GSV','image_coverage','image_coverage_bangkok.csv'))
df_area = df_area.drop(['Unnamed: 0','image_coverage'], axis = 1)
df_area['addrcode'] = df_area['addrcode'].astype(str)
df_area['image/area'] = df_area['image_area']/ df_area['land_area']
df_area['image/area'].loc[df_area['image/area'] > 1 ] = 1
df_area['image/area'] = df_area['image/area'].round(2)
df_area.head()

In [ ]:
df_pop = pd.read_csv(os.path.join('Data','Population','full-info','Bangkok-population-details.csv'))
df_pop = df_pop.drop('district', axis =1)
df_pop['addrcode'] = df_pop['addrcode'].astype(str)
df_pop.head()

In [ ]:
df_area_pop = pd.merge(df_area,df_pop, how = 'inner')
df_area_pop.head()

In [ ]:
df_area_pop['Age < 7_s'] = df_area_pop['Age < 7']*df_area_pop['image/area']
df_area_pop['Age < 7_s'] = df_area_pop['Age < 7_s'].round(3)
df_area_pop['Age 7 - 9_s'] = df_area_pop['Age 7 - 9']*df_area_pop['image/area']
df_area_pop['Age 7 - 9_s'] = df_area_pop['Age 7 - 9_s'].round(3)
df_area_pop['Age 10 - 14_s'] = df_area_pop['Age 10 - 14']*df_area_pop['image/area']
df_area_pop['Age 10 - 14_s'] = df_area_pop['Age 10 - 14_s'].round(3)
df_area_pop['Age 15 - 24_s'] = df_area_pop['Age 15 - 24']*df_area_pop['image/area']
df_area_pop['Age 15 - 24_s'] = df_area_pop['Age 15 - 24_s'].round(3)
df_area_pop['Age 25 - 34_s'] = df_area_pop['Age 25 - 34']*df_area_pop['image/area']
df_area_pop['Age 25 - 34_s'] = df_area_pop['Age 25 - 34_s'].round(3)
df_area_pop['Age 35 - 44_s'] = df_area_pop['Age 35 - 44']*df_area_pop['image/area']
df_area_pop['Age 35 - 44_s'] = df_area_pop['Age 35 - 44_s'].round(3)
df_area_pop['Age 45 - 60_s'] = df_area_pop['Age 45 - 60']*df_area_pop['image/area']
df_area_pop['Age 45 - 60_s'] = df_area_pop['Age 45 - 60_s'].round(3)
df_area_pop['Age > 60_s'] = df_area_pop['Age > 60']*df_area_pop['image/area']
df_area_pop['Age > 60_s'] = df_area_pop['Age > 60_s'].round(3)
df_area_pop.head()

In [ ]:
df_area_pop.to_csv('area_pop_bangkok.csv' , encoding = 'utf-8')

### District

In [ ]:
aggregation_function = {'land_area': 'sum', 'image_area' : 'sum', 'Age < 7' : 'sum', 'Age 7 - 9' : 'sum', 'Age 10 - 14' : 'sum', 'Age 15 - 24' : 'sum', 'Age 25 - 34' : 'sum', 'Age 35 - 44' : 'sum', 'Age 45 - 60' : 'sum', 'Age > 60' : 'sum'}
df_area_pop_dist = df_area_pop.groupby([df_area_pop['addrcode'].str[:4]]).aggregate(aggregation_function).reset_index()
df_area_pop_dist['image/area'] = df_area_pop_dist['image_area']/df_area_pop_dist['land_area']
df_area_pop_dist['image/area'] = df_area_pop_dist['image/area'].round(2)
df_area_pop_dist = df_area_pop_dist[['addrcode','land_area','image_area','image/area','Age < 7','Age 7 - 9','Age 10 - 14','Age 15 - 24','Age 25 - 34','Age 35 - 44','Age 45 - 60','Age > 60']]
df_area_pop_dist.head()

In [ ]:
df_area_pop_dist['Age < 7_s'] = df_area_pop_dist['Age < 7']*df_area_pop_dist['image/area']
df_area_pop_dist['Age < 7_s'] = df_area_pop_dist['Age < 7_s'].round(3)
df_area_pop_dist['Age 7 - 9_s'] = df_area_pop_dist['Age 7 - 9']*df_area_pop_dist['image/area']
df_area_pop_dist['Age 7 - 9_s'] = df_area_pop_dist['Age 7 - 9_s'].round(3)
df_area_pop_dist['Age 10 - 14_s'] = df_area_pop_dist['Age 10 - 14']*df_area_pop_dist['image/area']
df_area_pop_dist['Age 10 - 14_s'] = df_area_pop_dist['Age 10 - 14_s'].round(3)
df_area_pop_dist['Age 15 - 24_s'] = df_area_pop_dist['Age 15 - 24']*df_area_pop_dist['image/area']
df_area_pop_dist['Age 15 - 24_s'] = df_area_pop_dist['Age 15 - 24_s'].round(3)
df_area_pop_dist['Age 25 - 34_s'] = df_area_pop_dist['Age 25 - 34']*df_area_pop_dist['image/area']
df_area_pop_dist['Age 25 - 34_s'] = df_area_pop_dist['Age 25 - 34_s'].round(3)
df_area_pop_dist['Age 35 - 44_s'] = df_area_pop_dist['Age 35 - 44']*df_area_pop_dist['image/area']
df_area_pop_dist['Age 35 - 44_s'] = df_area_pop_dist['Age 35 - 44_s'].round(3)
df_area_pop_dist['Age 45 - 60_s'] = df_area_pop_dist['Age 45 - 60']*df_area_pop_dist['image/area']
df_area_pop_dist['Age 45 - 60_s'] = df_area_pop_dist['Age 45 - 60_s'].round(3)
df_area_pop_dist['Age > 60_s'] = df_area_pop_dist['Age > 60']*df_area_pop_dist['image/area']
df_area_pop_dist['Age > 60_s'] = df_area_pop_dist['Age > 60_s'].round(3)
df_area_pop_dist.head()

In [ ]:
df_area_pop_dist.to_csv('area_pop_bangkok_dist.csv' , encoding = 'utf-8')

## A * Container count / Population

### Subdistrict

In [ ]:
df_container = pd.read_csv(os.path.join('Data','Container Density','Subdistrict level','container_Bangkok_subdist.csv'))
df_container = df_container.drop('Unnamed: 0', axis = 1)
df_container['addrcode'] = df_container['addrcode'].astype(str)
df_container.head()

In [ ]:
df_pop = pd.read_csv(os.path.join('Data','Population','full-info','Bangkok-population-details.csv'))
df_pop = df_pop.drop('district', axis =1)
df_pop['addrcode'] = df_pop['addrcode'].astype(str)
df_pop.head()

In [ ]:
df_container_pop = pd.merge(df_container,df_pop, how = 'inner')
df_container_pop.head()

In [ ]:
df_pop_total = pd.read_csv(os.path.join('Data','Population','addrcode-index','Bangkok-population.csv'))
df_pop_total['addrcode'] = df_pop_total['addrcode'].astype(str)
#df_pop_total['addrcode'] = df_pop_total['addrcode'].str[:-2]
df_pop_total.head()

In [ ]:
df_container_pop = pd.merge(df_container_pop, df_pop_total, how = 'inner')
df_container_pop.head()

In [ ]:
#============
a = 10
#============
df_container_pop['Age < 7_bin'] = a * df_container_pop['bin'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_bin'] = df_container_pop['Age < 7_bin'].round(3)
df_container_pop['Age < 7_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_bowl'] = df_container_pop['Age < 7_bowl'].round(3)
df_container_pop['Age < 7_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_bucket'] = df_container_pop['Age < 7_bucket'].round(3)
df_container_pop['Age < 7_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_misc_short'] = df_container_pop['Age < 7_misc_short'].round(3)
df_container_pop['Age < 7_jar'] = a * df_container_pop['jar'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_jar'] = df_container_pop['Age < 7_jar'].round(3)
df_container_pop['Age < 7_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_pottedplant'] = df_container_pop['Age < 7_pottedplant'].round(3)
df_container_pop['Age < 7_tire'] = a * df_container_pop['tire'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_tire'] = df_container_pop['Age < 7_tire'].round(3)
df_container_pop['Age < 7_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_misc_tall'] = df_container_pop['Age < 7_misc_tall'].round(3)
df_container_pop['Age < 7_total'] = a * df_container_pop['total'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_total'] = df_container_pop['Age < 7_total'].round(3)

df_container_pop['Age 7 - 9_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_bin'] = df_container_pop['Age 7 - 9_bin'].round(3)
df_container_pop['Age 7 - 9_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_bowl'] = df_container_pop['Age 7 - 9_bowl'].round(3)
df_container_pop['Age 7 - 9_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_bucket'] = df_container_pop['Age 7 - 9_bucket'].round(3)
df_container_pop['Age 7 - 9_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_misc_short'] = df_container_pop['Age 7 - 9_misc_short'].round(3)
df_container_pop['Age 7 - 9_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_jar'] = df_container_pop['Age 7 - 9_jar'].round(3)
df_container_pop['Age 7 - 9_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_pottedplant'] = df_container_pop['Age 7 - 9_pottedplant'].round(3)
df_container_pop['Age 7 - 9_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_tire'] = df_container_pop['Age 7 - 9_tire'].round(3)
df_container_pop['Age 7 - 9_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_misc_tall'] = df_container_pop['Age 7 - 9_misc_tall'].round(3)
df_container_pop['Age 7 - 9_total'] = a * df_container_pop['total'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_total'] = df_container_pop['Age 7 - 9_total'].round(3)

df_container_pop['Age 10 - 14_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_bin'] = df_container_pop['Age 10 - 14_bin'].round(3)
df_container_pop['Age 10 - 14_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_bowl'] = df_container_pop['Age 10 - 14_bowl'].round(3)
df_container_pop['Age 10 - 14_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_bucket'] = df_container_pop['Age 10 - 14_bucket'].round(3)
df_container_pop['Age 10 - 14_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_misc_short'] = df_container_pop['Age 10 - 14_misc_short'].round(3)
df_container_pop['Age 10 - 14_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_jar'] = df_container_pop['Age 10 - 14_jar'].round(3)
df_container_pop['Age 10 - 14_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_pottedplant'] = df_container_pop['Age 10 - 14_pottedplant'].round(3)
df_container_pop['Age 10 - 14_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_tire'] = df_container_pop['Age 10 - 14_tire'].round(3)
df_container_pop['Age 10 - 14_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_misc_tall'] = df_container_pop['Age 10 - 14_misc_tall'].round(3)
df_container_pop['Age 10 - 14_total'] = a * df_container_pop['total'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_total'] = df_container_pop['Age 10 - 14_total'].round(3)

df_container_pop['Age 15 - 24_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_bin'] = df_container_pop['Age 15 - 24_bin'].round(3)
df_container_pop['Age 15 - 24_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_bowl'] = df_container_pop['Age 15 - 24_bowl'].round(3)
df_container_pop['Age 15 - 24_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_bucket'] = df_container_pop['Age 15 - 24_bucket'].round(3)
df_container_pop['Age 15 - 24_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_misc_short'] = df_container_pop['Age 15 - 24_misc_short'].round(3)
df_container_pop['Age 15 - 24_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_jar'] = df_container_pop['Age 15 - 24_jar'].round(3)
df_container_pop['Age 15 - 24_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_pottedplant'] = df_container_pop['Age 15 - 24_pottedplant'].round(3)
df_container_pop['Age 15 - 24_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_tire'] = df_container_pop['Age 15 - 24_tire'].round(3)
df_container_pop['Age 15 - 24_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_misc_tall'] = df_container_pop['Age 15 - 24_misc_tall'].round(3)
df_container_pop['Age 15 - 24_total'] = a * df_container_pop['total'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_total'] = df_container_pop['Age 15 - 24_total'].round(3)

df_container_pop['Age 25 - 34_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_bin'] = df_container_pop['Age 25 - 34_bin'].round(3)
df_container_pop['Age 25 - 34_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_bowl'] = df_container_pop['Age 25 - 34_bowl'].round(3)
df_container_pop['Age 25 - 34_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_bucket'] = df_container_pop['Age 25 - 34_bucket'].round(3)
df_container_pop['Age 25 - 34_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_misc_short'] = df_container_pop['Age 25 - 34_misc_short'].round(3)
df_container_pop['Age 25 - 34_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_jar'] = df_container_pop['Age 25 - 34_jar'].round(3)
df_container_pop['Age 25 - 34_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_pottedplant'] = df_container_pop['Age 25 - 34_pottedplant'].round(3)
df_container_pop['Age 25 - 34_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_tire'] = df_container_pop['Age 25 - 34_tire'].round(3)
df_container_pop['Age 25 - 34_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_misc_tall'] = df_container_pop['Age 25 - 34_misc_tall'].round(3)
df_container_pop['Age 25 - 34_total'] = a * df_container_pop['total'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_total'] = df_container_pop['Age 25 - 34_total'].round(3)

df_container_pop['Age 35 - 44_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_bin'] = df_container_pop['Age 35 - 44_bin'].round(3)
df_container_pop['Age 35 - 44_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_bowl'] = df_container_pop['Age 35 - 44_bowl'].round(3)
df_container_pop['Age 35 - 44_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_bucket'] = df_container_pop['Age 35 - 44_bucket'].round(3)
df_container_pop['Age 35 - 44_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_misc_short'] = df_container_pop['Age 35 - 44_misc_short'].round(3)
df_container_pop['Age 35 - 44_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_jar'] = df_container_pop['Age 35 - 44_jar'].round(3)
df_container_pop['Age 35 - 44_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_pottedplant'] = df_container_pop['Age 35 - 44_pottedplant'].round(3)
df_container_pop['Age 35 - 44_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_tire'] = df_container_pop['Age 35 - 44_tire'].round(3)
df_container_pop['Age 35 - 44_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_misc_tall'] = df_container_pop['Age 35 - 44_misc_tall'].round(3)
df_container_pop['Age 35 - 44_total'] = a * df_container_pop['total'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_total'] = df_container_pop['Age 35 - 44_total'].round(3)

df_container_pop['Age 45 - 60_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_bin'] = df_container_pop['Age 45 - 60_bin'].round(3)
df_container_pop['Age 45 - 60_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_bowl'] = df_container_pop['Age 45 - 60_bowl'].round(3)
df_container_pop['Age 45 - 60_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_bucket'] = df_container_pop['Age 45 - 60_bucket'].round(3)
df_container_pop['Age 45 - 60_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_misc_short'] = df_container_pop['Age 45 - 60_misc_short'].round(3)
df_container_pop['Age 45 - 60_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_jar'] = df_container_pop['Age 45 - 60_jar'].round(3)
df_container_pop['Age 45 - 60_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_pottedplant'] = df_container_pop['Age 45 - 60_pottedplant'].round(3)
df_container_pop['Age 45 - 60_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_tire'] = df_container_pop['Age 45 - 60_tire'].round(3)
df_container_pop['Age 45 - 60_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_misc_tall'] = df_container_pop['Age 45 - 60_misc_tall'].round(3)
df_container_pop['Age 45 - 60_total'] = a * df_container_pop['total'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_total'] = df_container_pop['Age 45 - 60_total'].round(3)

df_container_pop['Age > 60_bin'] = a * df_container_pop['bin'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_bin'] = df_container_pop['Age > 60_bin'].round(3)
df_container_pop['Age > 60_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_bowl'] = df_container_pop['Age > 60_bowl'].round(3)
df_container_pop['Age > 60_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_bucket'] = df_container_pop['Age > 60_bucket'].round(3)
df_container_pop['Age > 60_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_misc_short'] = df_container_pop['Age > 60_misc_short'].round(3)
df_container_pop['Age > 60_jar'] = a * df_container_pop['jar'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_jar'] = df_container_pop['Age > 60_jar'].round(3)
df_container_pop['Age > 60_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_pottedplant'] = df_container_pop['Age > 60_pottedplant'].round(3)
df_container_pop['Age > 60_tire'] = a * df_container_pop['tire'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_tire'] = df_container_pop['Age > 60_tire'].round(3)
df_container_pop['Age > 60_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_misc_tall'] = df_container_pop['Age > 60_misc_tall'].round(3)
df_container_pop['Age > 60_total'] = a * df_container_pop['total'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_total'] = df_container_pop['Age > 60_total'].round(3)

df_container_pop['Total_bin'] = a * df_container_pop['bin'] / df_container_pop['Total']
df_container_pop['Total_bin'] = df_container_pop['Total_bin'].round(3)
df_container_pop['Total_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Total']
df_container_pop['Total_bowl'] = df_container_pop['Total_bowl'].round(3)
df_container_pop['Total_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Total']
df_container_pop['Total_bucket'] = df_container_pop['Total_bucket'].round(3)
df_container_pop['Total_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Total']
df_container_pop['Total_misc_short'] = df_container_pop['Total_misc_short'].round(3)
df_container_pop['Total_jar'] = a * df_container_pop['jar'] / df_container_pop['Total']
df_container_pop['Total_jar'] = df_container_pop['Total_jar'].round(3)
df_container_pop['Total_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Total']
df_container_pop['Total_pottedplant'] = df_container_pop['Total_pottedplant'].round(3)
df_container_pop['Total_tire'] = a * df_container_pop['tire'] / df_container_pop['Total']
df_container_pop['Total_tire'] = df_container_pop['Total_tire'].round(3)
df_container_pop['Total_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Total']
df_container_pop['Total_misc_tall'] = df_container_pop['Total_misc_tall'].round(3)
df_container_pop['Total_total'] = a * df_container_pop['total'] / df_container_pop['Total']
df_container_pop['Total_total'] = df_container_pop['Total_total'].round(3)

In [ ]:
df_container_pop.head()

In [ ]:
df_container_pop.to_csv('a_container_pop_bangkok.csv', encoding = 'utf-8')

### [New Version]

In [ ]:
df_container_pop = pd.read_csv('Data/Correlation/a_container_pop_nst.csv')
df_container_pop = df_container_pop.drop('Unnamed: 0', axis = 1)
df_container_pop['addrcode'] = df_container_pop['addrcode'].astype(str)
df_container_pop.head()

In [ ]:
df_container_pop = df_container_pop.drop(['bin','bowl','bucket','misc_short','jar','pottedplant','tire','misc_tall','total','Age < 7','Age 7 - 9','Age 10 - 14','Age 15 - 24','Age 25 - 34','Age 35 - 44','Age 45 - 60', 'Age > 60'], axis = 1)
df_container_pop.head()

In [ ]:
df_dengue = pd.read_csv(os.path.join('Data','Dengue-cases','Dengue fever data','DF.csv'))
df_dengue['addrcode'] = df_dengue['addrcode'].astype(str)
df_dengue = df_dengue.loc[df_dengue['addrcode'].str[:2] == '80']
df_dengue = df_dengue.groupby(df_dengue['addrcode']).sum()
df_dengue = df_dengue.drop(['Year','WeekNum'],axis = 1)
df_dengue = df_dengue.reset_index()
df_dengue.head()

In [ ]:
df_pop_total = pd.read_csv(os.path.join('Data','Population','addrcode-index','NST-population.csv'))
df_pop_total['addrcode'] = df_pop_total['addrcode'].astype(str).str[:6]
df_pop_total['Total'] = df_pop_total['Total']/10000
df_pop_total.head()

In [ ]:
df_dengue0 = pd.DataFrame(df_dengue['addrcode'])
df_dengue0 = pd.merge(df_dengue0, df_dengue, how = 'inner')
df_dengue0 = pd.merge(df_dengue0, df_pop_total, how = 'inner')
df_dengue0['DF_0'] = df_dengue0['NumberCases']/df_dengue0['Total']
df_dengue0 = df_dengue0.iloc[:,[0,3]]
df_dengue0['addrcode'] = df_dengue0['addrcode'].astype(str)
df_dengue0 = pd.merge(df_dengue0, df_container_pop, how = 'inner')
df_dengue0.head()
df_dengue0.to_csv('DFw0_container_pop.csv', encoding = 'utf-8')

### District

In [ ]:
aggregation_function = {'bin': 'sum', 'bowl': 'sum', 'bucket': 'sum', 'misc_short': 'sum', 'jar': 'sum', 'pottedplant': 'sum', 'tire': 'sum', 'misc_tall': 'sum', 'total' : 'sum', 'Age < 7' : 'sum', 'Age 7 - 9' : 'sum', 'Age 10 - 14' : 'sum', 'Age 15 - 24' : 'sum', 'Age 25 - 34' : 'sum', 'Age 35 - 44' : 'sum', 'Age 45 - 60' : 'sum', 'Age > 60' : 'sum', 'Total' : 'sum'}
df_container_pop = df_container_pop.groupby([df_container_pop['addrcode'].str[:4]]).aggregate(aggregation_function).reset_index()
df_container_pop

In [ ]:
#============
a = 10
#============
df_container_pop['Age < 7_bin'] = a * df_container_pop['bin'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_bin'] = df_container_pop['Age < 7_bin'].round(3)
df_container_pop['Age < 7_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_bowl'] = df_container_pop['Age < 7_bowl'].round(3)
df_container_pop['Age < 7_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_bucket'] = df_container_pop['Age < 7_bucket'].round(3)
df_container_pop['Age < 7_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_misc_short'] = df_container_pop['Age < 7_misc_short'].round(3)
df_container_pop['Age < 7_jar'] = a * df_container_pop['jar'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_jar'] = df_container_pop['Age < 7_jar'].round(3)
df_container_pop['Age < 7_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_pottedplant'] = df_container_pop['Age < 7_pottedplant'].round(3)
df_container_pop['Age < 7_tire'] = a * df_container_pop['tire'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_tire'] = df_container_pop['Age < 7_tire'].round(3)
df_container_pop['Age < 7_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_misc_tall'] = df_container_pop['Age < 7_misc_tall'].round(3)
df_container_pop['Age < 7_total'] = a * df_container_pop['total'] / df_container_pop['Age < 7']
df_container_pop['Age < 7_total'] = df_container_pop['Age < 7_total'].round(3)

df_container_pop['Age 7 - 9_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_bin'] = df_container_pop['Age 7 - 9_bin'].round(3)
df_container_pop['Age 7 - 9_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_bowl'] = df_container_pop['Age 7 - 9_bowl'].round(3)
df_container_pop['Age 7 - 9_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_bucket'] = df_container_pop['Age 7 - 9_bucket'].round(3)
df_container_pop['Age 7 - 9_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_misc_short'] = df_container_pop['Age 7 - 9_misc_short'].round(3)
df_container_pop['Age 7 - 9_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_jar'] = df_container_pop['Age 7 - 9_jar'].round(3)
df_container_pop['Age 7 - 9_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_pottedplant'] = df_container_pop['Age 7 - 9_pottedplant'].round(3)
df_container_pop['Age 7 - 9_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_tire'] = df_container_pop['Age 7 - 9_tire'].round(3)
df_container_pop['Age 7 - 9_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_misc_tall'] = df_container_pop['Age 7 - 9_misc_tall'].round(3)
df_container_pop['Age 7 - 9_total'] = a * df_container_pop['total'] / df_container_pop['Age 7 - 9']
df_container_pop['Age 7 - 9_total'] = df_container_pop['Age 7 - 9_total'].round(3)

df_container_pop['Age 10 - 14_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_bin'] = df_container_pop['Age 10 - 14_bin'].round(3)
df_container_pop['Age 10 - 14_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_bowl'] = df_container_pop['Age 10 - 14_bowl'].round(3)
df_container_pop['Age 10 - 14_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_bucket'] = df_container_pop['Age 10 - 14_bucket'].round(3)
df_container_pop['Age 10 - 14_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_misc_short'] = df_container_pop['Age 10 - 14_misc_short'].round(3)
df_container_pop['Age 10 - 14_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_jar'] = df_container_pop['Age 10 - 14_jar'].round(3)
df_container_pop['Age 10 - 14_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_pottedplant'] = df_container_pop['Age 10 - 14_pottedplant'].round(3)
df_container_pop['Age 10 - 14_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_tire'] = df_container_pop['Age 10 - 14_tire'].round(3)
df_container_pop['Age 10 - 14_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_misc_tall'] = df_container_pop['Age 10 - 14_misc_tall'].round(3)
df_container_pop['Age 10 - 14_total'] = a * df_container_pop['total'] / df_container_pop['Age 10 - 14']
df_container_pop['Age 10 - 14_total'] = df_container_pop['Age 10 - 14_total'].round(3)

df_container_pop['Age 15 - 24_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_bin'] = df_container_pop['Age 15 - 24_bin'].round(3)
df_container_pop['Age 15 - 24_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_bowl'] = df_container_pop['Age 15 - 24_bowl'].round(3)
df_container_pop['Age 15 - 24_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_bucket'] = df_container_pop['Age 15 - 24_bucket'].round(3)
df_container_pop['Age 15 - 24_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_misc_short'] = df_container_pop['Age 15 - 24_misc_short'].round(3)
df_container_pop['Age 15 - 24_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_jar'] = df_container_pop['Age 15 - 24_jar'].round(3)
df_container_pop['Age 15 - 24_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_pottedplant'] = df_container_pop['Age 15 - 24_pottedplant'].round(3)
df_container_pop['Age 15 - 24_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_tire'] = df_container_pop['Age 15 - 24_tire'].round(3)
df_container_pop['Age 15 - 24_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_misc_tall'] = df_container_pop['Age 15 - 24_misc_tall'].round(3)
df_container_pop['Age 15 - 24_total'] = a * df_container_pop['total'] / df_container_pop['Age 15 - 24']
df_container_pop['Age 15 - 24_total'] = df_container_pop['Age 15 - 24_total'].round(3)

df_container_pop['Age 25 - 34_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_bin'] = df_container_pop['Age 25 - 34_bin'].round(3)
df_container_pop['Age 25 - 34_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_bowl'] = df_container_pop['Age 25 - 34_bowl'].round(3)
df_container_pop['Age 25 - 34_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_bucket'] = df_container_pop['Age 25 - 34_bucket'].round(3)
df_container_pop['Age 25 - 34_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_misc_short'] = df_container_pop['Age 25 - 34_misc_short'].round(3)
df_container_pop['Age 25 - 34_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_jar'] = df_container_pop['Age 25 - 34_jar'].round(3)
df_container_pop['Age 25 - 34_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_pottedplant'] = df_container_pop['Age 25 - 34_pottedplant'].round(3)
df_container_pop['Age 25 - 34_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_tire'] = df_container_pop['Age 25 - 34_tire'].round(3)
df_container_pop['Age 25 - 34_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_misc_tall'] = df_container_pop['Age 25 - 34_misc_tall'].round(3)
df_container_pop['Age 25 - 34_total'] = a * df_container_pop['total'] / df_container_pop['Age 25 - 34']
df_container_pop['Age 25 - 34_total'] = df_container_pop['Age 25 - 34_total'].round(3)

df_container_pop['Age 35 - 44_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_bin'] = df_container_pop['Age 35 - 44_bin'].round(3)
df_container_pop['Age 35 - 44_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_bowl'] = df_container_pop['Age 35 - 44_bowl'].round(3)
df_container_pop['Age 35 - 44_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_bucket'] = df_container_pop['Age 35 - 44_bucket'].round(3)
df_container_pop['Age 35 - 44_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_misc_short'] = df_container_pop['Age 35 - 44_misc_short'].round(3)
df_container_pop['Age 35 - 44_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_jar'] = df_container_pop['Age 35 - 44_jar'].round(3)
df_container_pop['Age 35 - 44_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_pottedplant'] = df_container_pop['Age 35 - 44_pottedplant'].round(3)
df_container_pop['Age 35 - 44_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_tire'] = df_container_pop['Age 35 - 44_tire'].round(3)
df_container_pop['Age 35 - 44_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_misc_tall'] = df_container_pop['Age 35 - 44_misc_tall'].round(3)
df_container_pop['Age 35 - 44_total'] = a * df_container_pop['total'] / df_container_pop['Age 35 - 44']
df_container_pop['Age 35 - 44_total'] = df_container_pop['Age 35 - 44_total'].round(3)

df_container_pop['Age 45 - 60_bin'] = a * df_container_pop['bin'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_bin'] = df_container_pop['Age 45 - 60_bin'].round(3)
df_container_pop['Age 45 - 60_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_bowl'] = df_container_pop['Age 45 - 60_bowl'].round(3)
df_container_pop['Age 45 - 60_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_bucket'] = df_container_pop['Age 45 - 60_bucket'].round(3)
df_container_pop['Age 45 - 60_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_misc_short'] = df_container_pop['Age 45 - 60_misc_short'].round(3)
df_container_pop['Age 45 - 60_jar'] = a * df_container_pop['jar'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_jar'] = df_container_pop['Age 45 - 60_jar'].round(3)
df_container_pop['Age 45 - 60_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_pottedplant'] = df_container_pop['Age 45 - 60_pottedplant'].round(3)
df_container_pop['Age 45 - 60_tire'] = a * df_container_pop['tire'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_tire'] = df_container_pop['Age 45 - 60_tire'].round(3)
df_container_pop['Age 45 - 60_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_misc_tall'] = df_container_pop['Age 45 - 60_misc_tall'].round(3)
df_container_pop['Age 45 - 60_total'] = a * df_container_pop['total'] / df_container_pop['Age 45 - 60']
df_container_pop['Age 45 - 60_total'] = df_container_pop['Age 45 - 60_total'].round(3)

df_container_pop['Age > 60_bin'] = a * df_container_pop['bin'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_bin'] = df_container_pop['Age > 60_bin'].round(3)
df_container_pop['Age > 60_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_bowl'] = df_container_pop['Age > 60_bowl'].round(3)
df_container_pop['Age > 60_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_bucket'] = df_container_pop['Age > 60_bucket'].round(3)
df_container_pop['Age > 60_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_misc_short'] = df_container_pop['Age > 60_misc_short'].round(3)
df_container_pop['Age > 60_jar'] = a * df_container_pop['jar'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_jar'] = df_container_pop['Age > 60_jar'].round(3)
df_container_pop['Age > 60_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_pottedplant'] = df_container_pop['Age > 60_pottedplant'].round(3)
df_container_pop['Age > 60_tire'] = a * df_container_pop['tire'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_tire'] = df_container_pop['Age > 60_tire'].round(3)
df_container_pop['Age > 60_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_misc_tall'] = df_container_pop['Age > 60_misc_tall'].round(3)
df_container_pop['Age > 60_total'] = a * df_container_pop['total'] / df_container_pop['Age > 60']
df_container_pop['Age > 60_total'] = df_container_pop['Age > 60_total'].round(3)

df_container_pop['Total_bin'] = a * df_container_pop['bin'] / df_container_pop['Total']
df_container_pop['Total_bin'] = df_container_pop['Total_bin'].round(3)
df_container_pop['Total_bowl'] = a * df_container_pop['bowl'] / df_container_pop['Total']
df_container_pop['Total_bowl'] = df_container_pop['Total_bowl'].round(3)
df_container_pop['Total_bucket'] = a * df_container_pop['bucket'] / df_container_pop['Total']
df_container_pop['Total_bucket'] = df_container_pop['Total_bucket'].round(3)
df_container_pop['Total_misc_short'] = a * df_container_pop['misc_short'] / df_container_pop['Total']
df_container_pop['Total_misc_short'] = df_container_pop['Total_misc_short'].round(3)
df_container_pop['Total_jar'] = a * df_container_pop['jar'] / df_container_pop['Total']
df_container_pop['Total_jar'] = df_container_pop['Total_jar'].round(3)
df_container_pop['Total_pottedplant'] = a * df_container_pop['pottedplant'] / df_container_pop['Total']
df_container_pop['Total_pottedplant'] = df_container_pop['Total_pottedplant'].round(3)
df_container_pop['Total_tire'] = a * df_container_pop['tire'] / df_container_pop['Total']
df_container_pop['Total_tire'] = df_container_pop['Total_tire'].round(3)
df_container_pop['Total_misc_tall'] = a * df_container_pop['misc_tall'] / df_container_pop['Total']
df_container_pop['Total_misc_tall'] = df_container_pop['Total_misc_tall'].round(3)
df_container_pop['Total_total'] = a * df_container_pop['total'] / df_container_pop['Total']
df_container_pop['Total_total'] = df_container_pop['Total_total'].round(3)

In [ ]:
df_container_pop.head()

In [ ]:
df_container_pop.to_csv('a_container_pop_bangkok_dist.csv', encoding = 'utf-8')

# DF and Container Pop_S

## Subdistrict

In [40]:
df_df100pop = pd.read_csv(os.path.join('Data','Dengue-cases','Dengue fever data','Manipulated','Subdistrict','DF_10000Population_details.csv'))
df_df100pop = df_df100pop.drop(['Unnamed: 0','NumberCases','population'], axis = 1)
df_df100pop['DFp10000Pop'] = df_df100pop['DFp10000Pop'] * 100
df_df100pop['addrcode'] = df_df100pop['addrcode'].astype(str)
df_df100pop.columns = ['addrcode','Year','WeekNum','DFp100Pop']
df_df100pop.head()

  addrcode  Year  WeekNum  DFp10000Pop
0   100101  2014        1          0.0
1   100101  2014        2          0.0
2   100101  2014        3          0.0
3   100101  2014        4          0.0
4   100101  2014        5          0.0

In [41]:
df_area_bkk = pd.read_csv(os.path.join('Data','Area and GSV','image_coverage','image_coverage_bangkok.csv'))
df_area_bkk = df_area_bkk.drop(['Unnamed: 0','image_coverage'], axis = 1)
df_area_bkk['addrcode'] = df_area_bkk['addrcode'].astype(str)

df_area_nst = pd.read_csv(os.path.join('Data','Area and GSV','image_coverage','image_coverage_nst.csv'))
df_area_nst = df_area_nst.drop(['Unnamed: 0','image_coverage'], axis = 1)
df_area_nst['addrcode'] = df_area_nst['addrcode'].astype(str)

df_area_krabi = pd.read_csv(os.path.join('Data','Area and GSV','image_coverage','image_coverage_krabi.csv'))
df_area_krabi = df_area_krabi.drop(['Unnamed: 0','image_coverage'], axis = 1)
df_area_krabi['addrcode'] = df_area_krabi['addrcode'].astype(str)

frame = [df_area_bkk, df_area_nst, df_area_krabi ]
df_area = pd.concat(frame)

df_area['image/area'] = df_area['image_area']/ df_area['land_area']
df_area['image/area'].loc[df_area['image/area'] > 1 ] = 1
df_area['image/area'] = df_area['image/area'].round(2)
df_area.head()

  addrcode  land_area  image_area  image/area
0   100101      14.11       16.16         1.0
1   100102       6.62        9.67         1.0
2   100103       1.97        3.32         1.0
3   100104       2.15        3.11         1.0
4   100105       1.39        3.46         1.0

In [42]:
df_pop_total = pd.read_csv(os.path.join('Data','Population','addrcode-index','Population.csv'))
df_pop_total['addrcode'] = df_pop_total['addrcode'].astype(str).str[:6]
df_pop_total.head()

  addrcode  Total
0   100101   3715
1   100102  11226
2   100103   3328
3   100104   3309
4   100105   3214

In [43]:
df_area_pop_total = pd.merge(df_area,df_pop_total, how = 'inner')
df_area_pop_total['total_s'] = df_area_pop_total['image/area'] * df_area_pop_total['Total']
df_area_pop_total = df_area_pop_total.iloc[:,[0,5]]
df_area_pop_total['addrcode'] = df_area_pop_total['addrcode'].astype(str)
df_area_pop_total.head()

  addrcode  total_s
0   100101   3715.0
1   100102  11226.0
2   100103   3328.0
3   100104   3309.0
4   100105   3214.0

In [44]:
df_container_bkk = pd.read_csv(os.path.join('Data','Container Density','Subdistrict level','container_bangkok_subdist.csv'))
df_container_bkk = df_container_bkk.drop('Unnamed: 0', axis = 1)
df_container_bkk['addrcode'] = df_container_bkk['addrcode'].astype(str)
df_container_nst = pd.read_csv(os.path.join('Data','Container Density','Subdistrict level','container_NST_subdist.csv'))
df_container_nst = df_container_nst.drop('Unnamed: 0', axis = 1)
df_container_nst['addrcode'] = df_container_nst['addrcode'].astype(str)
df_container_krabi = pd.read_csv(os.path.join('Data','Container Density','Subdistrict level','container_krabi_subdist.csv'))
df_container_krabi = df_container_krabi.drop('Unnamed: 0', axis = 1)
df_container_krabi['addrcode'] = df_container_krabi['addrcode'].astype(str)
frame = [df_container_bkk, df_container_nst ,df_container_krabi]
df_container_count = pd.concat(frame)
df_container_count = df_container_count.sort_values(['addrcode']).reset_index().drop('index', axis = 1)
df_container_count.head()

,addrcode,bin,bowl,bucket,misc_short,jar,pottedplant,tire,misc_tall,total
0,100101,46,7,44,11,2,145,14,12,281
1,100102,12,8,62,2,3,163,11,4,265
2,100103,12,6,28,3,2,93,5,0,149
3,100104,12,4,29,3,1,78,5,0,132
4,100105,11,11,61,11,2,156,14,2,268

In [45]:
df_new_cd = pd.DataFrame(df_container_count['addrcode'])
#==========
a = 10
#==========

df_new_cd['bin_pop9s'] = a * df_container_count.iloc[:,1]/df_area_pop_total.iloc[:,1]

df_new_cd['bowl_pop9s'] = a * df_container_count.iloc[:,2]/df_area_pop_total.iloc[:,1]

df_new_cd['bucket_pop9s'] = a * df_container_count.iloc[:,3]/df_area_pop_total.iloc[:,1]

df_new_cd['misc_short_pop9s'] = a * df_container_count.iloc[:,4]/df_area_pop_total.iloc[:,1]

df_new_cd['jar_pop9s'] = a * df_container_count.iloc[:,5]/df_area_pop_total.iloc[:,1]

df_new_cd['pottedplant_pop9s'] = a * df_container_count.iloc[:,6]/df_area_pop_total.iloc[:,1]

df_new_cd['tire_pop9s'] = a * df_container_count.iloc[:,7]/df_area_pop_total.iloc[:,1]

df_new_cd['misc_tall_pop9s'] = a * df_container_count.iloc[:,8]/df_area_pop_total.iloc[:,1]

df_new_cd['total_pop9s'] = a * df_container_count.iloc[:,9]/df_area_pop_total.iloc[:,1]

df_new_cd.head()
df_new_cd['addrcode'] = df_new_cd['addrcode'].astype(str)

In [47]:
df_df_pops = pd.merge(df_df100pop, df_new_cd, how = 'inner')
df_df_pops = df_df_pops.loc[df_df_pops['Year'] < 2018]
df_df_pops.head()

,addrcode,Year,WeekNum,DFp10000Pop,bin_pop9s,bowl_pop9s,bucket_pop9s,misc_short_pop9s,jar_pop9s,pottedplant_pop9s,tire_pop9s,misc_tall_pop9s,total_pop9s
0,100101,2014,1,0.0,0.123822,0.018843,0.118439,0.02961,0.005384,0.39031,0.037685,0.032301,0.756393
1,100101,2014,2,0.0,0.123822,0.018843,0.118439,0.02961,0.005384,0.39031,0.037685,0.032301,0.756393
2,100101,2014,3,0.0,0.123822,0.018843,0.118439,0.02961,0.005384,0.39031,0.037685,0.032301,0.756393
3,100101,2014,4,0.0,0.123822,0.018843,0.118439,0.02961,0.005384,0.39031,0.037685,0.032301,0.756393
4,100101,2014,5,0.0,0.123822,0.018843,0.118439,0.02961,0.005384,0.39031,0.037685,0.032301,0.756393

In [49]:
df_df_pops.to_csv('Data/Correlation/DF100Pop&CP.csv', encoding = 'utf-8')