In [2]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
import os
import matplotlib.pyplot as plt

In [3]:
# Load the Dengue dataset
#Dengue = datasets.load_Dengue()
df_train =  pd.read_csv(os.path.join('Data','Modeling','Training&Testing','train_subdist.csv'), header=0, skiprows=0)
df_train = df_train.drop('Unnamed: 0', axis = 1)
df_test = pd.read_csv(os.path.join('Data','Modeling','Training&Testing','test_subdist.csv'), header=0, skiprows=0)
df_test = df_test.drop('Unnamed: 0', axis = 1)
index = range(15)
df_result = pd.DataFrame(index = index,columns=['Deleted', 'Rsquared', 'RMSE', 'MAE', 'AIC'])

In [6]:
columns = df_train.columns.values.tolist()
    
for i in range(15):
    df_result['Deleted'][i] = columns[10+i]
    x_train = df_train.iloc[:,range(4,34)]
    x_train = x_train.drop(x_train.columns[i], axis=1)
    y_train = df_train.iloc[:,[3]]
    x_test = df_test.iloc[:,range(4,34)]
    x_test = x_test.drop(x_test.columns[i], axis=1)
    y_test = df_test.iloc[:,[3]]

    regressor = LinearRegression()
    regressor.fit(x_train, y_train)
    y_pred = regressor.predict(x_test)
    #print('Linear Regression R squared: %.4f' % regressor.score(x_test, y_test))
    df_result['Rsquared'][i] = regressor.score(x_test, y_test)

    # calculate RMSE
    lin_mse = mean_squared_error(y_pred, y_test)
    lin_rmse = np.sqrt(lin_mse)
    #print('Linear Regression RMSE: %.4f' % lin_rmse)
    df_result['RMSE'][i] = lin_mse

    # calculate MAE
    from sklearn.metrics import mean_absolute_error
    lin_mae = mean_absolute_error(y_pred, y_test)
    #print('Linear Regression MAE: %.4f' % lin_mae)
    df_result['MAE'][i] = lin_mae

    # calculate AIC
    resid = y_test - y_pred
    sse = sum(resid.values**2)
    k = 31
    AIC= 2*k - 2*np.log(sse)
    #print('Linear Regression AIC : %.4f' % AIC)
    #print('\n')
    df_result['AIC'][i] = AIC[0]

## Subdistrict Level

In [7]:
df_result

    Deleted   Rsquared      RMSE       MAE      AIC
0    DF_wm1  0.0134112  0.747763  0.486102  44.9676
1    DF_wm2  0.0305054  0.734807  0.481915  45.0025
2    DF_wm3   0.047957   0.72158  0.479865  45.0389
3    RF_wm1  0.0418851  0.726182  0.478362  45.0262
4    RF_wm2  0.0404916  0.727238  0.477485  45.0233
5    RF_wm3   0.040715  0.727069  0.477533  45.0237
6    RF_wm4  0.0415882  0.726407  0.477173  45.0255
7    RF_wm5  0.0407067  0.727075   0.47727  45.0237
8    RF_wm6  0.0413103  0.726617  0.477378   45.025
9   LST_wm1  0.0423516  0.725828  0.476021  45.0271
10  LST_wm2  0.0423558  0.725825  0.477248  45.0271
11  LST_wm3  0.0422013  0.725942  0.476241  45.0268
12  LST_wm4  0.0421524  0.725979  0.475891  45.0267
13  LST_wm5  0.0422538  0.725902  0.476325  45.0269
14  LST_wm6  0.0420955  0.726022  0.473552  45.0266

In [9]:
# Load the Dengue dataset
#Dengue = datasets.load_Dengue()
df_train =  pd.read_csv(os.path.join('Data','Modeling','Training&Testing','train_dist.csv'), header=0, skiprows=0)
#df_train = df_train.drop('Unnamed: 0', axis = 1)
df_test = pd.read_csv(os.path.join('Data','Modeling','Training&Testing','test_dist.csv'), header=0, skiprows=0)
#df_test = df_test.drop('Unnamed: 0', axis = 1)
index = range(15)
df_result = pd.DataFrame(index = index,columns=['Deleted', 'Rsquared', 'RMSE', 'MAE', 'AIC'])

In [10]:
columns = df_train.columns.values.tolist()
    
for i in range(15):
    df_result['Deleted'][i] = columns[10+i]
    x_train = df_train.iloc[:,range(4,34)]
    x_train = x_train.drop(x_train.columns[i], axis=1)
    y_train = df_train.iloc[:,[3]]
    x_test = df_test.iloc[:,range(4,34)]
    x_test = x_test.drop(x_test.columns[i], axis=1)
    y_test = df_test.iloc[:,[3]]

    regressor = LinearRegression()
    regressor.fit(x_train, y_train)
    y_pred = regressor.predict(x_test)
    #print('Linear Regression R squared: %.4f' % regressor.score(x_test, y_test))
    df_result['Rsquared'][i] = regressor.score(x_test, y_test)

    # calculate RMSE
    lin_mse = mean_squared_error(y_pred, y_test)
    lin_rmse = np.sqrt(lin_mse)
    #print('Linear Regression RMSE: %.4f' % lin_rmse)
    df_result['RMSE'][i] = lin_mse

    # calculate MAE
    from sklearn.metrics import mean_absolute_error
    lin_mae = mean_absolute_error(y_pred, y_test)
    #print('Linear Regression MAE: %.4f' % lin_mae)
    df_result['MAE'][i] = lin_mae

    # calculate AIC
    resid = y_test - y_pred
    sse = sum(resid.values**2)
    k = 31
    AIC= 2*k - 2*np.log(sse)
    #print('Linear Regression AIC : %.4f' % AIC)
    #print('\n')
    df_result['AIC'][i] = AIC[0]

## District Level

In [11]:
df_result

    Deleted  Rsquared     RMSE      MAE      AIC
0    DF_wm1  0.264585  6.87043   1.6928  44.4968
1    DF_wm2  0.263983  6.87605  1.70002  44.4952
2    DF_wm3  0.290829  6.62524  1.69216  44.5695
3    RF_wm1  0.284445  6.68489  1.68239  44.5516
4    RF_wm2  0.294492  6.59103  1.66638  44.5798
5    RF_wm3   0.28967  6.63608  1.67602  44.5662
6    RF_wm4  0.290256   6.6306  1.67462  44.5679
7    RF_wm5  0.291248  6.62133  1.67312  44.5707
8    RF_wm6   0.29089  6.62468  1.67451  44.5696
9   LST_wm1  0.290282  6.63036  1.67502  44.5679
10  LST_wm2  0.290412  6.62914   1.6752  44.5683
11  LST_wm3  0.289918  6.63376  1.67587  44.5669
12  LST_wm4  0.290196  6.63115  1.67594  44.5677
13  LST_wm5  0.290549  6.62786  1.67512  44.5687
14  LST_wm6  0.290772  6.62578  1.67006  44.5693